services:
  shared_postgres:
    image: postgres:16-alpine
    container_name: shared_postgres
    restart: always
    mem_limit: 1024m
    cpus: 1.5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-StrongPostgres@123}
      POSTGRES_DB: ${POSTGRES_DB:-devops_prod}
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB", "-c", "work_mem=4MB"]
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_STORAGE:-postgres_data}:/var/lib/postgresql/data
      - ${INFRA_BASE_DIR:-/var/www/vps-infra}/volumes/db/postgres/backups:/backups
    networks:
      - traefik_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    mem_limit: 256m
    cpus: 0.5
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SUPERADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${SUPERADMIN_PASSWORD:-NC+P4aVcpuCK7TAx8SQM}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - ${INFRA_BASE_DIR:-/var/www/vps-infra}/volumes/db/pgadmin:/var/lib/pgadmin
      - ${INFRA_BASE_DIR:-/var/www/vps-infra}/volumes/db/pgadmin-config/config_local.py:/pgadmin4/config_local.py
    ports:
      - "5050:80"
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin-http.rule=Host(`${PGADMIN_HOST:-pgadmin.example.com}`)"
      - "traefik.http.routers.pgadmin-http.entrypoints=web"
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_HOST:-pgadmin.example.com}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

volumes:
  postgres_data:
    name: ${POSTGRES_DATA_STORAGE:-postgres_data}

networks:
  traefik_net:
    name: traefik_net
    external: true
